v1.0.3 新增功能和修复问题
halo-dev/plugin-sitemap pull request #16
Opened 2023-09-01 08:45 UTC by carolcoral

## Change
为了解决了站点在使用反向代理、NG代理、CDN回源等情况下，domain://sitemap.xml 中的站点地址与实际期望的访问地址不一致问题

* 新增自定义站点地址功能（手动可控）
* 调整地址权重为 1.0

## FIX

* 修复站点xml中时间为文章的最后更新时间（非刷新时间，tags等依然保留刷新时间机制）

2023-09-01 09:01 UTC, JohnNiang commented
关于 Site URL 的配置问题，我有一个建议：

Halo 目前在 [HaloProperties](https://github.com/halo-dev/halo/blob/2baf6aeb31906599e5fee9b833a2801c637434a8/application/src/main/java/run/halo/app/infra/properties/HaloProperties.java#L32) 中提供了 `externalUrl` 的配置，主要是为了避免用户在各个插件都手动配置它。这里建议直接调用 [ExternalURLSupplier#getURL(HttpRequest)](https://github.com/halo-dev/halo/blob/2baf6aeb31906599e5fee9b833a2801c637434a8/api/src/main/java/run/halo/app/infra/ExternalUrlSupplier.java#L32)方法获取 Site URL。这里将优先返回用户配置的 `halo.externalUrl`，其次才会解析当前用户所请求的域名。

如果无法正常获取当前用户所请求的域名，大概率是因为反向代理工具（如 Nginx）没有正确代理 `X-Forward-For` 头。

2023-09-05 06:58 UTC, JohnNiang commented
Hi @carolcoral ,我发现在当前版本中无法正常调用 ExternalUrlSupplier#getURL(HttpRequest) 方法，我将尝试升级一下 Halo 的依赖来支持。

2023-09-07 08:22 UTC, JohnNiang commented on src/main/java/run/halo/sitemap/SitemapPluginConfig.java
> +                    }
```suggestion
                var url = externalUrlSupplier.getURL(request.exchange().getRequest());
                String prioritySetting = baseSetting.getPriority().trim();
                double priority = 1.0d;
                if (StringUtils.isNotEmpty(prioritySetting)) {
                    priority = Double.parseDouble(prioritySetting);
                }
                options = SitemapGeneratorOptions.builder()
                    .siteUrl(url)
                    .priority(priority)
                    .build();
```

2023-09-07 08:22 UTC, JohnNiang commented on src/main/java/run/halo/sitemap/SitemapPluginConfig.java
> +    private URL toUrl(String siteUrl) {
如果以上改动被接受了，这个方法似乎不会被用到，建议删除。

2023-09-07 08:22 UTC, JohnNiang commented on src/main/resources/extensions/settings.yaml
> +          name: siteUrl
如果以上修改被接受，建议删除 siteUrl 的配置。

2023-09-08 06:17 UTC, guqing commented on README.md
> +> 声明： 本插件从 [plugin-sitemap v1.0.2](https://github.com/halo-sigs/plugin-sitemap) 代码升级而来，不进行自动应用商店发布
不要提交与问题无关的更改到 PR，下同

2023-09-08 06:31 UTC, guqing requested changes

2023-09-08 06:31 UTC, guqing commented on src/main/java/run/halo/sitemap/SitemapPluginConfig.java
> +        this.baseSetting = this.settingFetcher.fetch(BaseSetting.GROUP, BaseSetting.class)
不建议在构造函数中使用 settingFetcher 将 BaseSetting 存储到对象，这会导致用户更改设置后不生效（始终使用的旧值）

2023-09-08 06:31 UTC, guqing commented on src/main/java/run/halo/sitemap/SitemapGeneratorOptions.java
> +    private double priority = 1.0;
这里修改默认值为 1 有什么依据吗

2023-09-08 06:31 UTC, guqing commented on src/main/java/run/halo/sitemap/CachedSitemapGetter.java
> +                        .collectList()
<img width="675" alt="image" src="https://github.com/halo-sigs/plugin-sitemap/assets/38999863/5d466bd6-4459-4843-b255-b26758f27089">
设置 IDEA 将 `Preferences -> Editor -> code style -> Enable EditorConfig support` 勾选上后重新格式化代码，并且不建议直接全局格式化，改动了哪些代码就选中后格式化哪些

2023-09-20 01:34 UTC, carolcoral commented on src/main/java/run/halo/sitemap/SitemapGeneratorOptions.java
> +    private double priority = 1.0;
后续自定义修改权重参数值后，仅会变动“文章”类地址的权重，因此设置默认权重为“1.0”作为全局的基础参考值

2023-09-20 01:34 UTC, carolcoral commented on src/main/java/run/halo/sitemap/CachedSitemapGetter.java
> +                        .collectList()
经过查看本地idea中已经勾选，可能是pull过程或其他原因导致了全局格式化，抱歉

2023-09-20 01:35 UTC, carolcoral commented on src/main/java/run/halo/sitemap/SitemapPluginConfig.java
> +        this.baseSetting = this.settingFetcher.fetch(BaseSetting.GROUP, BaseSetting.class)
嗯，这个是要考虑到的问题，因此在说明中特别强调需要“重启插件”才可以生效

2023-09-20 01:38 UTC, carolcoral commented on src/main/resources/extensions/settings.yaml
> +          name: siteUrl
非常抱歉无法接受以上修改。因为本次升级主要针对有“反向代理”、“FRP穿透”等特殊需求的用户。如果使用自动获取地址其实是可以获取到有效地址的，但是经过CDN-源站-反向代理操作后的地址与实际访问站点地址（即期望搜索引擎进行收录展示的有效地址）完全不一致了。通常常规用户不需要特别设置自定义参数中的相关配置。

2023-09-20 03:15 UTC, carolcoral commented
## change
1. 删除无效类
2. 变更自定义站点参数为动态获取（不再需要重启插件）
3. 解决代码冲突合并robots.txt 功能

2023-09-20 03:16 UTC, carolcoral commented on src/main/java/run/halo/sitemap/SitemapPluginConfig.java
> +    private URL toUrl(String siteUrl) {
已删除该方法

2023-09-20 03:18 UTC, carolcoral commented
> 关于 Site URL 的配置问题，我有一个建议：
> 
> Halo 目前在 [HaloProperties](https://github.com/halo-dev/halo/blob/2baf6aeb31906599e5fee9b833a2801c637434a8/application/src/main/java/run/halo/app/infra/properties/HaloProperties.java#L32) 中提供了 `externalUrl` 的配置，主要是为了避免用户在各个插件都手动配置它。这里建议直接调用 [ExternalURLSupplier#getURL(HttpRequest)](https://github.com/halo-dev/halo/blob/2baf6aeb31906599e5fee9b833a2801c637434a8/api/src/main/java/run/halo/app/infra/ExternalUrlSupplier.java#L32)方法获取 Site URL。这里将优先返回用户配置的 `halo.externalUrl`，其次才会解析当前用户所请求的域名。
> 
> 如果无法正常获取当前用户所请求的域名，大概率是因为反向代理工具（如 Nginx）没有正确代理 `X-Forward-For` 头。

不仅仅是存在NG代理设置问题导致的获取站点地图和期望地址不一致问题。同时存在多重穿透和CDN源站方式导致的获取到的站点地址加上了源站地址的端口（实际上访问地址是没有端口的，仅源站存在端口）

2023-09-20 04:23 UTC, guqing commented on src/main/java/run/halo/sitemap/SitemapGeneratorOptions.java
> +    private double priority = 1.0;
> 后续自定义修改权重参数值后，仅会变动“文章”类地址的权重，因此设置默认权重为“1.0”作为全局的基础参考值

不建议将默认值改为1，google 在未指定 priority 的情况下默认为主页 1.0 级别，所有其他页面为 0.5 级别，而常见的 priority 设置参考为：
1.0-0.8
主页、产品信息、登陆页面。

0.7-0.4
新闻文章、博客文章、天气服务等。而分类页、标签页、作者页一般会设置为 0.5

0.3-0.0
常见问题解答、过时的信息、旧的新闻稿等

参考文章：https://www.contentpowered.com/blog/xml-sitemap-priority-changefreq/

2023-09-20 04:27 UTC, guqing commented
希望一个 PR 只单纯的解决一个问题，不要在一个 PR 中做多件事，并且希望先提一个 issue 来与之关联让我们知道到底发生了什么事

2023-09-22 01:39 UTC, carolcoral commented
> 希望一个 PR 只单纯的解决一个问题，不要在一个 PR 中做多件事，并且希望先提一个 issue 来与之关联让我们知道到底发生了什么事，不然会给 reviewer 带来困扰。
> 
> 目前你的 PR 包含了之前已经合并的改动，很难 review，建议：
> 
> ```shell
> # https or ssh
> git remote add upstream https://github.com/halo-dev/plugin-sitemap.git
> git fetch upstream/main
> git merge upstream/main
> git reset --soft upstream/main
> git add .
> git commit -m '这里改为你的提交信息'
> git push origin HEAD -f
> ```
> 
> 参考 https://git-scm.com/docs/git-reset

解决ISSUE：
1. https://github.com/halo-dev/plugin-sitemap/issues/13
2. https://github.com/halo-dev/plugin-sitemap/issues/11
3. https://github.com/halo-dev/plugin-sitemap/issues/10

因为PR最开始仅仅解决 https://github.com/halo-dev/plugin-sitemap/issues/11 但未被接受PR。因此后续的commit被依次提交了。

2023-09-22 03:42 UTC, carolcoral commented
目前来看：
1. 对ISSUE中的3个问题已经全部解决
    1. 支持自定义站点地址
        * NAS代理可能导致的期望访问地址和实际获取地址不一致(NAS部署服务，外部访问使用了隐性URL访问会导致该问题)
        * 返回的站点地图信息中地址存在端口(使用CDN回源源站域名会导致该问题)
    3. 支持自定义权重（针对全局权重一致无法对文章类权重进行变更的需求）
4. 支持自定义设置动态修改加载

如果依然不符合您的要求，请直接关闭当前PR吧，不想折腾了

2023-09-25 02:54 UTC, ruibaby commented
> 如果依然不符合您的要求，请直接关闭当前PR吧，不想折腾了

实际上 reset 之后重新 commit 并强制推送即可，不过依旧感谢你参与贡献。

针对这个问题已经有了一个新的 PR：<https://github.com/halo-dev/plugin-sitemap/pull/25>，欢迎 Review 和测试。

/close

2023-09-25 02:54 UTC, closed without merging