feat: support robots.txt router
halo-dev/plugin-sitemap pull request #19
Opened 2023-09-14 02:09 UTC by AirboZH

新增支持 robots.txt 路由以及编辑 robots.txt 规则

示例站点: https://airbozh.tech/robots.txt

由于更希望以绝对地址来显示sitemap，所以规则设置中省去了sitemap的设置
统一设置为host/sitemap.xml，这与插件的sitemap路由一致

2023-09-15 03:14 UTC, guqing requested changes

2023-09-15 03:14 UTC, guqing commented on src/main/resources/extensions/settings.yml
> +            Disallow:
```suggestion
            Allow: /
```

2023-09-15 03:14 UTC, guqing commented on src/main/resources/extensions/settings.yml
> +          help: 编写robots.txt规则
```suggestion
          help: 编写 robots.txt 规则
```

2023-09-15 03:34 UTC, AirboZH commented on src/main/java/run/halo/sitemap/SitemapPluginConfig.java
> +                if (!setting.get("robots_txt_enable").asText().equals("true")) {
设置中有一个 robots_txt_enable 的判断，如果这里改为启用，yml中这个判断也要加一个 `NOT` 这个逻辑。
```yml
        - $formkit: textarea
          if: $get(robots_txt_enable).value
          name: rules
          label: 规则
```

yml中的判断和上述判断逻辑是相反的，总得有一个地方验证 `NOT` 这个逻辑吧，改为 disable可能不会简单些。
---------
默认排除 /console 的抓取的意思是就算robots_txt是关闭的也输出下面内容？
```
User-agent: *
Disallow: /console
```

2023-09-15 04:03 UTC, guqing commented on src/main/java/run/halo/sitemap/SitemapPluginConfig.java
> +                if (!setting.get("robots_txt_enable").asText().equals("true")) {
我想了一下, 那还是叫做 enable 把，我感觉 robots.txt 路由需要存在并排除 console，后续可能希望扩展 robots.txt 给其他插件使用来排除不需要抓取的规则，所以这里的 enable 的 label 可以叫做启用自定义规则，默认关闭，然后在代码中添加 console 的禁用作为默认规则会不会好一些，还需要默认排除 .js 和 .css 文件的抓取

2023-09-15 04:33 UTC, AirboZH commented on src/main/java/run/halo/sitemap/SitemapPluginConfig.java
> +                if (!setting.get("robots_txt_enable").asText().equals("true")) {
我看了一下网上一般的配置，具体的规则还需要再讨论一下
[搜索引擎优化 (SEO) 新手指南#向 Google 和用户呈现相同的网页](https://developers.google.com/search/docs/fundamentals/seo-starter-guide?visit_id=638303485897615090-1702048741&rd=1&hl=zh-cn#googleseeyourpage)
不建议排除 .js 和 .css 文件
然后我参考了wordpress的常用规则
```
1、Disallow: /wp-admin/、Disallow: /wp-content/和Disallow: /wp-includes/
用于告诉搜索引擎不要抓取后台程序文件页面。

2、Disallow: /*/comment-page-*和Disallow: /*?replytocom=*
禁止搜索引擎抓取评论分页等相关链接。

3、Disallow: /category/*/page/和Disallow: /tag/*/page/
禁止搜索引擎抓取收录分类和标签的分页。

4、Disallow: /*/trackback
禁止搜索引擎抓取收录trackback等垃圾信息

5、Disallow: /feed、Disallow: /*/feed和Disallow: /comments/feed
禁止搜索引擎抓取收录feed链接，feed只用于订阅本站，与搜索引擎无关。

6、Disallow: /?s=*和Disallow: /*/?s=*\
禁止搜索引擎抓取站内搜索结果

7、Disallow: /attachment/
禁止搜索引擎抓取附件页面，比如毫无意义的图片附件页面。
```
参考这个规则，我想到几个可以排除的
1. 后台 /console
2. 特殊页面 /categories/* 和 /tags/* 和 /link
![image](https://github.com/halo-sigs/plugin-sitemap/assets/50261327/8fa33369-a141-41d7-a9a1-241042cc1052)

![image](https://github.com/halo-sigs/plugin-sitemap/assets/50261327/84315ff3-77cb-44e1-8fc2-1d3563ba7189)
3. 订阅链接 /rss /sitemap.xml
4. 用户设置的文件存储（这个也有可能用户想让搜索引擎爬取，或者可以做配置）

目前就想到这些，欢迎补充

2023-09-15 05:08 UTC, AirboZH commented on src/main/java/run/halo/sitemap/SitemapPluginConfig.java
> +                if (!setting.get("robots_txt_enable").asText().equals("true")) {
看了一下互联网主流网站，一般不对爬虫做太多细节限制
淘宝： http://www.taobao.com/robots.txt
微博： https://www.weibo.com/robots.txt
B站： https://www.bilibili.com/robots.txt
Github：https://github.com/robots.txt
内容平台
掘金: https://juejin.cn/robots.txt
知乎：https://www.zhihu.com/robots.txt 只留了/search-special没什么参考价值
网易新闻： https://news.163.com/robots.txt

2023-09-15 08:33 UTC, guqing commented on src/main/java/run/halo/sitemap/SitemapPluginConfig.java
> +                if (!setting.get("robots_txt_enable").asText().equals("true")) {
可以，前期不需要很完善，主要是 console

2023-09-15 08:53 UTC, AirboZH commented
等一下，可能需要做一下缓存控制。测试发现robots.txt会被缓存，配置更新不及时

2023-09-15 09:07 UTC, AirboZH commented
已解决，可以review了

2023-09-15 09:34 UTC, guqing requested changes

2023-09-15 09:34 UTC, guqing commented on src/main/java/run/halo/sitemap/SitemapPluginConfig.java
> +                    .header("Cache-Control","no-cache")
```suggestion
                    .cacheControl(CacheControl.noCache())
```

2023-09-15 09:34 UTC, guqing commented on src/main/java/run/halo/sitemap/SitemapPluginConfig.java
> +                        .header("Cache-Control","no-cache")
```suggestion
                        .cacheControl(CacheControl.noCache())
```

2023-09-15 10:20 UTC, guqing reviewed
/approve

2023-09-18 02:40 UTC, guqing commented
/ping @halo-dev/sig-halo

2023-09-18 03:52 UTC, ruibaby requested changes

2023-09-18 03:52 UTC, ruibaby commented on src/main/resources/extensions/settings.yml
> +      label: robots设置
```suggestion
      label: robots.txt 设置
```

2023-09-18 04:04 UTC, guqing commented on src/main/resources/extensions/settings.yml
> +          name: robots_txt_enable
这里直接改为 enable 就好了

2023-09-18 04:06 UTC, guqing commented on src/main/java/run/halo/sitemap/SitemapPluginConfig.java
> +                var sitemapURL = "Sitemap: "+uri+"sitemap.xml";
格式化一下代码，+ 前后有空格，其他地方也一样

2023-09-18 04:10 UTC, ruibaby reviewed
/lgtm

2023-09-18 04:12 UTC, guqing commented on src/main/java/run/halo/sitemap/SitemapPluginConfig.java
> +                if (!setting.get("robots_txt_enable").asText().equals("true")) {
改为 enable 之后这里忘记改了

2023-09-18 05:44 UTC, ruibaby approved these changes
/lgtm

2023-09-18 07:22 UTC, merged